FROM debian:stable-slim

ENV DEBIAN_FRONTEND=noninteractive

# Instalar dependencias
RUN apt update && \
    apt install -y wget curl perl nano percona-toolkit default-mysql-client && \
    wget http://mysqltuner.pl/ -O /usr/local/bin/mysqltuner && \
    chmod +x /usr/local/bin/mysqltuner

RUN echo "\nssl=FALSE" >> /etc/mysql/my.cnf
    
CMD ["tail", "-f", "/dev/null"]
    