{
 "title": "MySQL - PLAX Dashboard 01",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cantidad y estado de Hilos ejecutandose",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexiones activas",
   "type": "stat",
   "description": "mysql_global_status_threads_connected",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "title": "QPS (Queries por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])"
    }
   ]
  },
  {
   "title": "Lecturas Lógicas de InnoDB por Segundo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests[1m])"
    }
   ]
  },
  {
   "title": "Cantidad de veces que una query tuvo que esperar por un lock.",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_row_lock_waits"
    }
   ]
  },
  {
   "title": "Uso de CPU del proceso mysqld",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 15 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Escrituras Lógicas de InnoDB por Segundo",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_writes[1m])"
    }
   ]
  }
 ]
}